config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  root to: 'users#index'

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :create, :new, :destroy] do
      resources :likes, only: [:new, :create]
      resources :comments, only: [:new, :create, :destroy]
    end
  end
  
  namespace :api do
    resources :users do
      resources :posts do
        resources :comments
      end
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.admin?
      can :manage, :all
    else
      can :read, :all
      can :create, Post, :all
      can :destroy, Post, author_id: user.id
      can :create, Comment, :all
      can :destroy, Comment, author_id: user.id
    end
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post, class_name: 'Post'

  after_save :update_comment_counter
  after_destroy :update_comment_counter

  def update_comment_counter
    post.update(comments_counter: post.comments.count)
  end

  def as_json(options = {})
    super({ only: %i[text author_id post_id] }.merge(options))
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post, class_name: 'Post'

  after_save :update_likes_counter

  def update_likes_counter
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, foreign_key: 'post_id', dependent: :destroy
  has_many :likes, foreign_key: 'post_id', dependent: :destroy
  belongs_to :author, class_name: 'User'

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0 }

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  after_save :update_post_counter
  after_destroy :update_post_counter

  def update_post_counter
    author.update(posts_counter: author.posts.count)
  end

  # Option 2: Working with the default #as_json method
  def as_json(options = {})
    super({ only: %i[title text] }.merge(options))
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, foreign_key: 'author_id', dependent: :destroy
  has_many :likes, foreign_key: 'author_id', dependent: :destroy

  validates :name, presence: true
  validates :posts_counter, numericality: { greater_than_or_equal_to: 0 }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @post = Post.find(request.params['post_id'])
    render json: @post.comments.all
  end

  def create
    comment_params = params.require(:comment).permit(:author_id, :post_id, :text)

    @user = User.find(comment_params[:author_id])
    @post = Post.find(comment_params[:post_id])
    @comment = @post.comments.create(comment_params)
    @comment.post_id = @post.id
    if @comment.save
      render json: { status: 'OK!' }
    else
      render json: { status: 'Ho no!' }
    end
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  def index
    @user = User.find(request.params['user_id'])
    render json: @user.posts.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in) do |user_params|
      user_params.permit(:email, :encrypted_password)
    end

    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:name, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:post_id])
    @comment = Comment.new(comment_params)
    @comment.author = current_user
    @comment.post = @user.posts.find(params['post_id'])
    respond_to do |format|
      if @comment.save
        format.html { redirect_to user_post_path(@user, @post) }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to user_posts_path(current_user), notice: 'Comment destroyed successfully' }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.new(like_params)
    @like.author = current_user
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) } if @like.save
    end
  end

  def like_params
    params.permit(:author_id, :post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments, :author)
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
    @comments = @post.comments.includes(:author)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    @post.author = current_user
    @post.comments_counter = 0
    @post.likes_counter = 0

    respond_to do |format|
      if @post.save
        format.html { redirect_to user_posts_path }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    @post = Post.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to user_posts_path(current_user), notice: 'Post was successfully removed.' }
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<h1>New Comment</h1>
<%= form_with model: @comment, url: user_post_comments_path do |form| %>
    <div class="form">
    <div class="form-field">
      <%= form.label :comment %> <br>
      <%= form.text_area :text, required: true %>
    </div>
    <%= form.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice p-3"><%= notice %></p>
    <p class="alert p-3"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<%= render('users/user_card', user: @user) %>
<%= link_to new_user_post_path() do %>
  <button>New Post</button>
<% end %>
<div class="posts-container">
  <% @posts.each do |post| %>
    <div class="post-and-comments">
      <%= link_to user_post_path(@user, post) do %>
        <div class="post">
          <h4>Post <%= post.id %> - <%= post.title %> comments: <%= post.comments_counter %>, likes: <%= post.likes_counter %></h4>
          <p><%= post.text %></p>
          <%if can? :destroy, post %>
          <%= link_to "Delete", user_post_path(@user, post),
           data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
          <% end %>
        </div>
      <% end %>
      <% if post.comments.length.positive? %>
        <div class="comments">
            <% post.recent_comments.each do |comment| %>
              <p><%= comment.text.truncate(80, separator: ' ' ) %></p>
              <%if can?  :destroy, comment %>
              <%= link_to "Delete Comment", user_post_comment_path(comment.author_id, comment.post_id, comment),
               data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }
               %>
            <% end %>
            <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
  <button>Pagination</button>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= form_with model: @post, url: user_posts_path do |form| %>
  <div class="form">
    <div class="form-field">
      <%= form.label :title %> <br>
      <%= form.text_field :title, required: true %>
    </div>

    <div class="form-field">
      <%= form.label :post_text %> <br>
      <%= form.text_area :text, required: true %>
    </div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/show.html.erb
<div class="posts-container post-and-comments">
  <div class="full-post">
    <h4>Post #<%= @post.id %> by <%= @user.name %></h4>
    <p class='post-counters'>Comments <%= @post.comments_counter %>, Likes <%= @post.likes_counter %></p>
    <p class='post-text'><%= @post.text %></p>
    <%= form_with model: Like.new, url: user_post_likes_path(@user, @post) do |form| %>
        <% form.submit :Like %>
      <% end %>
  </div>
  <%= link_to new_user_post_comment_path(@user, @post) do %>
    <button>New Comment</button>
  <% end %>
  <% if @post.comments.length.positive? %>
    <div class="comments">
        <% @post.comments.each do |comment| %>
          <p><%= comment.author.name %>: <%= comment.text %></p>
        <% end %>
    </div>
  <% end %>

</div>

app/views/users/_user_card.html.erb
<div class='user-card'>
  <img src=<%= user.photo %> alt=<%= user.name %>>
  <div>
    <h2><%= user.name %></h2>
    <p class='post-count' >Number of posts: <%= user.posts_counter %></p>
  </div>
</div>

app/views/users/index.html.erb
<% if current_user %>
      <h2 class="mt-3">Welcome <%= current_user.name %></h2>
      <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "bg-red-400 hover:bg-red-700 text-white font-medium py-2 px-4 rounded focus:outline-none focus:shadow-outline pointer-events-auto", 'data-ripple-light': true, data: { turbo: false } %>
<% end %>
<ul>
  <% @users.each do |user| %>
    <li> 
    <%= link_to(render('user_card', user: user), user_path(user)) %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<%= render('user_card', user: @user) %>
<div class="user-info">
  <p><span>Bio: <br></span><%= @user.bio %></p>
  <% @user.recent_posts.each do |post|%>
    <%= link_to user_post_path(@user, post) do %>
      <div class="post">
        <h4>Post #<%= post.id %></h4>
        <p><%= post.text.truncate(100, separator: ' ') %></p>
      </div>
    <% end %>
  <% end %>
  <button><%= link_to('See all posts', user_posts_path(@user)) %></button>
</div>